workspace = { members = [ 
  ".", 
  # "admin-control-panel" 
] }

[package]
name = "web-img-manager"
version = "1.3.0"
edition = "2021"
authors = ["Serveny"]
license = "MIT"

[[bin]]
name = "web-img-manager"
path = "src/main.rs"

[features]
default = []
openssl = ["dep:openssl", "actix-web/openssl"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.5"
actix-web = { version = "4.9.0"}
actix-web-actors = "4.3.1"
actix-cors = "0.7.0"
sanitize-filename = "0.5.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
base64 = "0.22.1"
image = "0.25.2"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
log = "0.4.22"
env_logger = "0.11.5"
regex = "1.10.6"
rand = "0.8.5"
actix-multipart = "0.7.2"
reqwest = { version = "0.12.7", features = ["json", "multipart"] }
ts-rs = {version ="9.0.1", features = ["serde-compat", "uuid-impl"] }
image_hasher = "2.0.0"
openssl = { version = "0.10.66", features = ["vendored"], optional = true }
tokio = { version = "1.40.0" }