workspace = { members = [ 
  ".", 
  # "admin-control-panel" 
] }

[package]
name = "web-img-manager"
version = "0.1.0"
edition = "2021"
authors = ["Serveny"]
license = "MIT"

[[bin]]
name = "web-img-manager"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4.2"
actix-cors = "0.7"
sanitize-filename = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
image = "0.25"
uuid = { version = "1.6", features = ["v4", "serde"] }
log = "0.4"
env_logger = "0.11"
regex = "1"
rand = "0.8"
actix-multipart = "0.6.2"
reqwest = { version = "0.12", features = ["json"] }
ts-rs = {version ="8.1", features = ["serde-compat", "uuid-impl"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }