[package]
name = "web-img-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
sanitize-filename = "0.5"
serde = { version = "1", features = ["derive"] }
base64 = "0.21"
image = "0.24"
uuid = { version = "1.6", features = ["v4"] }
actix-cors = "0.7.0"
env_logger = "0.10.1"
