version: '3.4'

services:
  webimgmanager:
    image: web-img-manager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '1870:1870'
    volumes:
      - wim-storage:/

volumes:
  wim-storage:
