version: '3.4'

services:
  webimgmanager:
    image: web-img-manager
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080'
    volumes:
      - img_storage:/

volumes:
  img_storage:
